### ISSUE TITLE
Make it possible to self-host Prototypo again

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#146]
Currently the app is tied to our own remote servers and you need an account to use it, even if you install it locally.
It should be possible to self-host it entirely and configure a different backend location.

**Comment by gambhiro** [comment]
I followed the steps in the README and in the hoodie docs, and I've got a local app running. I suppose this issue is resolved then?

**Comment by FranzPoize** [comment]
Yep. Thx for the feedback on the doc. Did you encounter any difficulties ?

**Comment by gambhiro** [comment]
@FranzPoize The only gotcha was to use the couchdb port (not the app or admin port) for the cors proxy, i.e. `:6003` by default:

    corsproxy http://127.0.0.1:6003/ --port=9595 --origin=http://localhost:9000 --credentials

Which is printed in the console, and follows from the README too, but because hoodie opens the `:6001` address in the browser, and then gets you use the `:6002` for the admin interface, one gets preoccupied with these.

**Comment by gambhiro** [comment]
@FranzPoize I remembered now there were some missing dependencies when starting the app, I had to install `xxhashjs` and `whatwg-fetch`.
