### ISSUE TITLE
templates.js not getting created

### ISSUE THREAD

**Issue by ronnieduke** [byte-foundry/prototypo#178]
Hello,

After running through all the instructions and typing "grunt serve", I see the application structure and CSS, but I am getting console errors:

 http://localhost:9000/.tmp/templates/templates.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9000/genese.ptf/dist/font.json?typeface=default Failed to load resource: the server responded with a status of 404 (Not Found)

Looking in my .tmp directory, all I see is the /styles directory.

I am using the "prototypo2" branch on OSX using angular 1.3.15.

Any help would be much appreciated. Thanks!

**Comment by louisremi** [comment]
Hi, we're working on a large update and are getting close to merging on master. This should make local installation much easier.

**Comment by damirka** [comment]
Well, if installation becomes easier more people are able to help by giving advice, testing or maybe developing. Don't you think?

**Comment by louisremi** [comment]
Of course, this is exactly what we're trying to do.

**Comment by damirka** [comment]
We'll see.

**Comment by ronnieduke** [comment]
@louisremi - Thanks for the update! Looking forward to the update. Can you ping this thread when the merge is made?

**Comment by FranzPoize** [comment]
Hi @ronnieduke , the new master branch is up. I change the readme.md to reflect the change that has been made to prototypo (the only big change is that we now use gulp instead of grunt because our beards were too long to continue using grunt).

If you want to setup your own hoodie app, I'll update the doc on how to install a hoodie app and how to configure prototypo to use that app during the week. Here is hoodie doc http://docs.hood.ie/en/start/ on how to set up an app.

**Comment by ronnieduke** [comment]
@FranzPoize - haha sounds great! I look forward to testing it out!

**Comment by FranzPoize** [comment]
The documentation is updated https://github.com/byte-foundry/prototypo/blob/master/README.md#running-prototypo-with-you-own-hoodie-app
