### ISSUE TITLE
’.is-disabled’ efficiency

### ISSUE THREAD

**Issue by raphaelbastide** [byte-foundry/prototypo#269]
Removing `.is-disabled` class allow users to bypass the demo limitations. It should be impossible or at least more difficult, unless you want to attribute hackers some privileges. :computer:

**Comment by FranzPoize** [comment]
Hi, the code is open source and you can install prototypo for free on your own server, thus we do not see a point in providing a firmer security. Since all the application is executed on your browser there will always be a lot of way to circumvent the basic application authentication. If you want to use our application for free by installing on your local machine we're totally ok with it. However we do really appreciate it if you decide to pay our monthly subscription :D

**Comment by davelab6** [comment]
Isn't this like the nytimes "paywall" cookie, and woff - a simple 'fence'
that is trivial to work around but signals an attempt to ask users to pay
for the value of the work, so if you work around it you are actively not
supporting the project?
