### ISSUE TITLE
Glyphs Panel Blank

### ISSUE THREAD

**Issue by Noskill1343** [byte-foundry/prototypo#561]
I don't know what this panel called, but please check my screenshot.
I tried clear browser cache, tried different browser (Chrome and Opera), and that panel still blank.
When I first tried I can see and edit the glyphs there, but today I have this issue.

![prototypo](https://cloud.githubusercontent.com/assets/26031912/23335189/5321595c-fbe2-11e6-87f2-bc36111fa5f5.jpg)

**Comment by Aldrian** [comment]
Hi! 
Thanks for submitting this issue. Some users are contacting us about this on Intercom as well.
A temporary fix while we are investigating this would be to go to the view settings and click on "reset view" as shown on the screenshot below.
![Reset view](https://uploads.intercomcdn.com/i/o/17697314/c8d53b73b22967595a825d28/reset+view.jpg)

You can also double click on the glyph view to reset it.

I hope that will do the trick for you. I'll close this issue when this problem is solved in a more durable way.

**Comment by Noskill1343** [comment]
Hi Aldrian,

Thank you for your reply, it works :)
