### ISSUE TITLE
Cannot read property '0' of undefined in delete-family action

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#702]
## Description
Ok this will be a bit cryptic but this is from this trackJS log https://my.trackjs.com/details/c89f9514993844dab98b563c5f03b69d

On the transition to start from dashboard there is to be a delete-family call. And it crash on the https://github.com/byte-foundry/prototypo/blob/4717afc4e6c11aef7c1a2e9d1087aed4266eac59/app/scripts/actions/font.actions.jsx#L349

Classified as High because this seems to crash the font creation

## Callback
Please notify [the user](https://app.intercom.io/a/apps/mnph1bst/users/5b50a79f3da9f57db1392528/all-conversations) on intercom that the bug they reported is fixed

**Comment by Aldrian** [comment]
Fixed in c6b07d02fbe1cc6e6461512525c2b211bfd03756
Deleting the last family (Most likely getting back to the start page from the onboarding) was causing a crash, because previously the app wasn't allowing this action from the UI.
I just did a check, and the dashboard already has a fallback to go to /start if no font is loaded.

Should we merge this to master right away @FranzPoize?
