### ISSUE TITLE
Why shut it down instead of maintaining it for passive income

### ISSUE THREAD

**Issue by wentin** [byte-foundry/prototypo#783]
Hi dear creator, I was a customer (not very active but loved it when using it and happily paid for the service). I am really surprised and sad to find out it is no longer operative. I am in need of the tool and there is no alternative on the market. Why not run it as a passive income stream instead of shutting it down? If the server cost outweighs the subscription, I am happy to chip in to support it!

**Comment by yannickmathey** [comment]
Hey! Thank you for your support : ) Actually there is no dev anymore in the team ; at the shutdown, we didn't migrate from GraphCool to Prisma and they also shut down the service on July 2020. That's why there is no online version anymore… But some users reported that an older version is still working on localhost : https://github.com/byte-foundry/prototypo/issues/767

**Comment by stknstn** [comment]
Yannick, this app is so cool I'd be into resuscitating it from its ashes... can we talk about it?

**Comment by yannickmathey** [comment]
Hey, sure we can. But as I mentioned earlier, I'm not a technical person, and apart from the information available in this repo, I'm not sure how I could help make it happen. I think this thread is the right place for the discussion and to possibly get support from others. What are your questions @stknstn ?
